import { useNavigate } from "react-router-dom";
import { Link } from "react-router-dom";
import { Icons } from "../components/icons";

const Section = ({ title, children }) => (
  <section className="mb-10">
    <h2 className="text-white text-lg font-semibold mb-3">{title}</h2>
    <div className="text-neutral-400 text-sm leading-relaxed space-y-3">{children}</div>
  </section>
);

const PrivacyPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      <header className="sticky top-0 z-10 bg-neutral-950/90 backdrop-blur-md border-b border-neutral-800 px-4 py-3 flex items-center gap-3">
        <button
          onClick={() => navigate(-1)}
          className="p-2 rounded-full hover:bg-neutral-800 transition-colors"
          aria-label="Go back"
        >
          <Icons.back className="w-5 h-5 text-white" />
        </button>
        <Icons.logo className="w-7 h-7" />
        <span className="text-white font-semibold">Privacy Policy</span>
      </header>

      <main className="max-w-2xl mx-auto px-5 py-10">
        <p className="text-neutral-500 text-xs mb-10">Last updated: May 7, 2026</p>

        <p className="text-neutral-400 text-sm leading-relaxed mb-10">
          At Gossips, your privacy matters. This Privacy Policy explains what information we
          collect, how we use it, and the choices you have. This policy applies to the Gossips
          platform, including our website, mobile applications, and all related services
          (collectively, the "Service").
        </p>

        <Section title="1. Information We Collect">
          <p>We collect information you provide directly, information generated by your use of the Service, and information from third parties.</p>

          <p><strong className="text-white">Account Information.</strong> When you create an account, we collect your name, email address, phone number (if provided), username, and password. You may also optionally provide a profile photo, bio, and other profile details.</p>

          <p><strong className="text-white">Content You Create.</strong> We collect the content you post, share, send, or receive through the Service, including photos, videos, text, comments, messages, and reactions.</p>

          <p><strong className="text-white">Device & Technical Information.</strong> We automatically collect information about the devices you use to access the Service, including IP address, browser type and version, operating system, device identifiers, crash reports, and diagnostic data.</p>

          <p><strong className="text-white">Usage Information.</strong> We collect information about how you interact with the Service, such as the features you use, the content you view, searches you perform, time spent on the Service, and referring URLs.</p>

          <p><strong className="text-white">Location Information.</strong> With your permission, we may collect precise location data. We also derive approximate location from your IP address regardless of permission.</p>

          <p><strong className="text-white">Cookies & Tracking Technologies.</strong> We use cookies, web beacons, pixels, and similar technologies to collect information about your browsing activity. See our{" "}
            <Link to="/cookies" className="text-white underline underline-offset-2">Cookies Policy</Link>{" "}
            for details.
          </p>

          <p><strong className="text-white">Third-Party Login.</strong> If you sign in using Google or another third-party service, we receive information from that provider, such as your name, email address, and profile photo, in accordance with the permissions you grant and that provider's privacy policy.</p>

          <p><strong className="text-white">Communications.</strong> If you contact us directly (e.g., for support), we retain records of that correspondence.</p>
        </Section>

        <Section title="2. How We Use Information">
          <p>We use the information we collect to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong className="text-white">Provide and improve the Service</strong> — to operate, maintain, and deliver the features of Gossips, process transactions, and perform technical operations.</li>
            <li><strong className="text-white">Personalize your experience</strong> — to tailor content, recommendations, and features based on your interests and activity.</li>
            <li><strong className="text-white">Communications</strong> — to send you service-related notifications, security alerts, and updates about the Service. We may also send promotional communications if you opt in.</li>
            <li><strong className="text-white">Advertising</strong> — to display relevant ads, measure ad effectiveness, and support our advertising partners. You can adjust ad preferences in Settings.</li>
            <li><strong className="text-white">Safety & security</strong> — to detect, prevent, and respond to fraud, abuse, security incidents, and violations of our{" "}
              <Link to="/terms" className="text-white underline underline-offset-2">Terms of Service</Link>.
            </li>
            <li><strong className="text-white">Analytics & research</strong> — to understand usage trends, measure the effectiveness of features, and conduct research to improve the Service.</li>
            <li><strong className="text-white">Legal compliance</strong> — to comply with applicable laws, legal processes, and governmental requests.</li>
          </ul>
        </Section>

        <Section title="3. How We Share Information">
          <p>We do not sell your personal information. We share your information only in the following circumstances:</p>

          <p><strong className="text-white">With Other Users.</strong> Content you post publicly is visible to other users. Your username, profile photo, and public posts are accessible to all Gossips users. Direct messages are visible only to the intended recipients.</p>

          <p><strong className="text-white">Service Providers.</strong> We share information with trusted third-party vendors who help us operate the Service (e.g., cloud hosting, analytics, customer support, email delivery). These providers are contractually bound to protect your information and may not use it for any purpose other than providing services to us.</p>

          <p><strong className="text-white">Legal Requests.</strong> We may disclose information in response to valid legal requests such as subpoenas, court orders, or government demands, or when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or comply with the law.</p>

          <p><strong className="text-white">Business Transfers.</strong> If Gossips is involved in a merger, acquisition, or sale of assets, your information may be transferred. We will provide notice before your personal information becomes subject to a different privacy policy.</p>

          <p><strong className="text-white">With Your Consent.</strong> We may share your information with third parties when you give us explicit consent to do so.</p>
        </Section>

        <Section title="4. Cookies & Tracking Technologies">
          <p>We use cookies and similar tracking technologies to operate the Service, remember your preferences, and deliver personalized content and advertising. For a detailed explanation of the types of cookies we use and how to manage them, please see our{" "}
            <Link to="/cookies" className="text-white underline underline-offset-2">Cookies Policy</Link>.
          </p>
        </Section>

        <Section title="5. Data Retention">
          <p>We retain your personal information for as long as your account is active or as needed to provide you with the Service. We also retain information as necessary to comply with legal obligations, resolve disputes, and enforce our agreements.</p>
          <p>When you delete your account, we will delete or anonymize your personal information within 90 days, except where retention is required by law or where the content has been shared with others (e.g., messages sent to other users may be retained by the recipient). Certain aggregated and anonymized data may be retained indefinitely for analytics purposes.</p>
        </Section>

        <Section title="6. Your Rights">
          <p>Depending on your location, you may have certain rights regarding your personal information:</p>

          <p><strong className="text-white">Access & Portability.</strong> You have the right to request a copy of the personal information we hold about you in a portable format.</p>

          <p><strong className="text-white">Correction.</strong> You have the right to request that we correct inaccurate or incomplete personal information about you.</p>

          <p><strong className="text-white">Deletion.</strong> You have the right to request deletion of your personal information. You can delete your account from Settings, or submit a deletion request to{" "}
            <a href="mailto:privacy@gossips.app" className="text-white underline underline-offset-2">privacy@gossips.app</a>.
          </p>

          <p><strong className="text-white">Restriction & Objection.</strong> In certain circumstances, you have the right to restrict or object to our processing of your personal information.</p>

          <p><strong className="text-white">GDPR (EEA/UK Users).</strong> If you are located in the European Economic Area or United Kingdom, you have rights under the General Data Protection Regulation (GDPR), including the rights listed above. Our legal bases for processing include performance of a contract (providing the Service), legitimate interests, consent, and legal compliance.</p>

          <p><strong className="text-white">CCPA (California Residents).</strong> If you are a California resident, you have the right to know what personal information we collect, to delete it, to opt out of its "sale" (as defined under the CCPA), and to non-discrimination for exercising your rights. We do not sell personal information as defined by the CCPA. To exercise your rights, contact us at{" "}
            <a href="mailto:privacy@gossips.app" className="text-white underline underline-offset-2">privacy@gossips.app</a>.
          </p>

          <p>To exercise your rights, please contact us at{" "}
            <a href="mailto:privacy@gossips.app" className="text-white underline underline-offset-2">privacy@gossips.app</a>.
            We will respond to verified requests within 30 days (or within the legally required timeframe).
          </p>
        </Section>

        <Section title="7. Children's Privacy">
          <p>The Service is not directed to children under 13 years of age. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete that information promptly.</p>
          <p>For users in jurisdictions where the applicable age threshold is 16 (such as certain EU member states), we apply heightened protections for users between 13 and 16 and require verifiable parental consent before processing their data beyond what is strictly necessary to provide the Service.</p>
          <p>If you are a parent or guardian and believe your child has created an account without your consent, please contact us at{" "}
            <a href="mailto:privacy@gossips.app" className="text-white underline underline-offset-2">privacy@gossips.app</a>.
          </p>
        </Section>

        <Section title="8. International Data Transfers">
          <p>Gossips operates globally. Your information may be transferred to, stored, and processed in countries other than your own, including countries that may not have the same data protection laws as your home country.</p>
          <p>For users in the EEA, UK, or Switzerland, we rely on appropriate safeguards for international data transfers, including Standard Contractual Clauses (SCCs) approved by the European Commission, or other legally recognized transfer mechanisms, where applicable.</p>
        </Section>

        <Section title="9. Security Measures">
          <p>We take reasonable technical and organizational measures to protect your personal information against unauthorized access, loss, destruction, or alteration. These measures include encryption of data in transit (TLS/HTTPS), access controls, regular security audits, and employee training.</p>
          <p>However, no method of transmission over the Internet or electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your information, we cannot guarantee absolute security. In the event of a data breach that affects your rights or freedoms, we will notify you and relevant authorities as required by applicable law.</p>
        </Section>

        <Section title="10. Changes to This Privacy Policy">
          <p>We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. When we make material changes, we will notify you by updating the "Last updated" date at the top of this page and, where appropriate, by sending an in-app notification or email.</p>
          <p>We encourage you to review this Privacy Policy periodically. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the updated policy.</p>
        </Section>

        <Section title="11. Contact / Data Protection Officer">
          <p>If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:</p>
          <ul className="list-none space-y-1">
            <li>
              Privacy inquiries:{" "}
              <a href="mailto:privacy@gossips.app" className="text-white underline underline-offset-2">
                privacy@gossips.app
              </a>
            </li>
            <li>
              Data Protection Officer:{" "}
              <a href="mailto:dpo@gossips.app" className="text-white underline underline-offset-2">
                dpo@gossips.app
              </a>
            </li>
          </ul>
          <p>EEA/UK users may also lodge a complaint with their local supervisory authority.</p>
        </Section>

        <div className="pt-6 border-t border-neutral-800 flex flex-wrap gap-4 text-xs text-neutral-500">
          <Link to="/terms" className="hover:text-white transition-colors">Gossips Terms</Link>
          <Link to="/cookies" className="hover:text-white transition-colors">Cookies Policy</Link>
        </div>
      </main>
    </div>
  );
};

export default PrivacyPage;
